# .github/workflows/deploy_sitemain.yml

name: Build and deploy Node.js app to Azure Web App - sitemain

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Permissão necessária para o checkout

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Instalar dependências e construir app
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Compactar artefato
        run: zip release.zip ./* -r

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artefato
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Descompactar artefato
        run: unzip release.zip

      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy para Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sitemain'
          slot-name: 'Production'
          package: .
